import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import 'bootstrap/dist/css/bootstrap.min.css'; 
import { ReactNode } from 'react';
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{backgroundImage: 'linear-gradient(to right,rgb(85, 106, 118),rgb(86, 110, 122))'}}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
